### ISSUE TITLE
Add abillity to specify semiColons and tabChars

### ISSUE THREAD

**Issue by laggingreflex** [gajus/create-index#19]
To support coding styles ([standard](https://www.npmjs.com/package/standard)) that prefer not to have semi-colons. 

It could be added with a switch `--no-semi-colons`

Similarly `--tab-char='\t'` or `--tab-char='    '`

**Comment by gajus** [comment]
Just add `./index.js` to `.eslintrc`. There can be so many different styles.

Or see this and consider raising a PR, https://github.com/gajus/create-index/issues/14.
