### ISSUE TITLE
Does not work with filename using dash.

### ISSUE THREAD

**Issue by moimael** [gajus/create-index#26]
Hi,

I tried your project on a directory from our project and it seems that all files that have a default export but a dash in their filename are ignored. All files without dash are correctly added to the index.js file.

Thanks.

**Comment by moimael** [comment]
It's probably related to this part of the code : 

```javascript
const isSafeName = (fileName) => {
  return /^[a-z][a-z0-9._]+$/i.test(fileName);
};
```

**Comment by gajus** [comment]
Thats because variable names containing dash are not valid export names.

**Comment by moimael** [comment]
So if I understand correctly the filename will be used for the export statement by create-index ? Can't you just camelize those ? Since it's default export and not named one the variable name do not matter.

**Comment by gajus** [comment]
That would encourage a bad style pattern… see https://github.com/selaux/eslint-plugin-filenames#matching-exported-values-match-exported

**Comment by gajus** [comment]
The point is that all these need to be the same:

* the file name
* the export name
* the import name

```js
// Foo.js

export default class Foo {}
```

```js
// index.js
import Foo from './Foo';

```

Doing anything else is just shooting yourself in a foot.

**Comment by moimael** [comment]
We use the convention : 
file name: standard-header.js
export: default so no name.
import: StandardHeader

I don't see how this is shooting ourselves in the foot.
Anyway i will find another solution, thanks for your time.

**Comment by gajus** [comment]
> We use the convention :
> file name: standard-header.js
> export: default so no name. (some of our files export js objects directly)
> import: StandardHeader

Change it to `StandardHeader` or `standardHeader`. Whats the problem?

**Comment by moimael** [comment]
The problem is the filename, `standard-header.js` is not picked by the script, it's just ignored but `locations.js` is picked. How we import it does not matter it was just to explain our conventions.

**Comment by gajus** [comment]
> The problem is the filename, standard-header.js is not picked by the script and I dont want to rename dozens of files and change everyones habit for no good reasons.

Thats what I have meant by shooting yourself in a foot. You are just trying to work around style inconsistency issue, not fix it.

**Comment by moimael** [comment]
It was a chosen convention and a very widespread one in the js world. I get that you don't like it but it doesn't make it wrong.

http://stackoverflow.com/questions/7273316/what-is-the-javascript-filename-naming-convention

**Comment by gajus** [comment]
Do not guide your code style solely by popular vote.

Think about implications of using dash characters in the name.

The best tip I can give is, make all variable names match the following regex: `^[A-Z]?[a-z]+(?:[A-Z][a-z]+)*$`. That means:

* no special characters
* no numbers
* only PascalCase or camelCase
* no MULtiple uppercases in a row

This will save you a lot of headaches.

For not-popular but smart style guide, see https://github.com/gajus/eslint-config-canonical.

Sure, all of this is personal preference based. Though that preference is based on delivering hundreds of projects.

**Comment by allthesignals** [comment]
@moimael were you able to fork this and build the feature yourself? I'm working within a framework too and our particular business needs prohibit forking that framework and refactoring to follow a convention for naming files.

**Comment by mrchief** [comment]
Its a very standard practice to have filenames in kebab-case and exports as camelCase. Even the plugin supports this: `"filenames/match-exported": [ 2, "kebab" ]`.

This is a bad case of a tool with confused objectives. Is the tool's purpose to help automate a manual process or is its purpose to be filename/exports linting rule enforcer?

**Comment by lprajus2007** [comment]
I agree 100% with the file name conventions argument but if you are in a point of no return like me and deliberately want to shoot yourself in the foot here's a package I published with an additional option `-s` to skip the filename safety check -

`npx create-index-plus <target-directory> -s -x <file-extension>`
