### ISSUE TITLE
Requires 2 passes to include the index created in the 1st pass

### ISSUE THREAD

**Issue by laggingreflex** [gajus/create-index#28]
If you have a directory structure like this:
```
foo
   bar
      baz.js
```
and you create index recursively using the new `--recursive` flag it first creates `foo/bar/index.js` with `baz` export, but when it creates `foo/index.js` it doesn't include the `bar` export that was just created. If you run the command again only then it creates/updates `foo/index.js` with the `bar` export.

I'm guessing this is because on the first pass when it walks the directory tree `foo/bar/index.js` doesn't exist yet. 

It should include the indexes it itself will be creating in the directory tree.

**Comment by gajus** [comment]
Irrelevant.

See:

* https://github.com/gajus/create-index/pull/18
* https://github.com/gajus/create-index/pull/27
