### ISSUE TITLE
Feature request: Excluding specific files

### ISSUE THREAD

**Issue by hinok** [gajus/create-index#31]
Hey,
It's just proposal of a new feature that could be very handy.

I would like to exclude some files which are added to generated index.js files, why?
I have a folder `/icons` witch contains all my icons (each icon is a react component).
In this folder I have also `stories.js` file (I'm using [react-storybook](https://github.com/storybooks/react-storybook)). Now `stories.js` is always added to the end of the file and my storybook is broken.

I think that it could work also for other people in other more advanced cases.
I could implement it and add PR but before I would like to talk about proposed solutions.

## 1. Using a "special comment" in generated `index.js` file

```
// @create-index
// @create-index-ignore: [/stories.(js)$/]

export Abc from './Abc.js';
export Zxc from './Zxc.js';
export Qwe from './Qwe.js';
```

## .2 Using a "special configuration file" `.create-index` inside a specific directory

`.create-index`

```
{
  ignore: [
    /stories.(js)$/
  ]
}
```

**Comment by gajus** [comment]
I don't think it makes sense to use a configuration file (yes another dot-file in the project for no good reason).

I'd say a variation of providing configuration in comment is a good approach, e.g.

```js
// @create-index {"ignore": ["stories.(js)$"]}

```

1. We keep the `// @create-index` comment as it.
2. We change the [`// @create-index` check](https://github.com/gajus/create-index/blob/7353f043943c920b08c3d13b5779909a3a3f3123/src/utilities/validateTargetDirectory.js#L36) to allow arbitrary string to follow the comment.
3. We require assume that anything that follows `// @create-index` (on the same line) is a configuration object (defined as JSON).

This needs to be done in two PRs: (1) enable the above logic, (2) add `ignore` configuration.

This is quite a substantial amount of work. Though, if you'd raise the PRs, I'd be happy to review and and publish it.

**Comment by advance512** [comment]
Was any work done on this feature?

**Comment by hinok** [comment]
@advance512 I had an unexpected problem with my health and I couldn't start working on it in the last few weeks. I think that I'll be able to start implementation in the next week.

**Comment by advance512** [comment]
Feel well, @hinok! Thanks for any help :)
