### ISSUE TITLE
Add option to uppercase first char of export

### ISSUE THREAD

**Issue by OmgImAlexis** [gajus/create-index#38]
I'd like to be able to use this for mongoose models. Typically the models are imported with their first char capitalised such as `import {Comment, Post, User} from 'models';` from what I can tell the vars are exported using the filenames and I'd rather not have to rename my files `Post.js`, etc. as it will clash with my linting rules for file names.

**Comment by OmgImAlexis** [comment]
If you're okay with this and can give me an ideal name for the option I'll open a PR for this.

**Comment by gajus** [comment]
> vars are exported using the filenames and I'd rather not have to rename my files Post.js, etc. as it will clash with my linting rules for file names.
> [..]
> If you're okay with this and can give me an ideal name for the option I'll open a PR for this.

Nop. Not a good idea. File names must match import names.

**Comment by OmgImAlexis** [comment]
According to what guideline/spec?

**Comment by gajus** [comment]
> According to what guideline/spec?

My personal preference.
