### ISSUE TITLE
Files with hyphen are ignored.

### ISSUE THREAD

**Issue by snekse** [gajus/create-index#49]
A file named `fizz-buzz.js` would be ignored by `npx create-index ./`

If they are not supported, some kind of output would be nice.  Maybe a comment in the created index file for why something was skipped?  

Ideally the hyphenated name would be camel-cased. 
e.g. `export { default as fizzBuzz} from 'fizz-buzz'`

**Comment by gajus** [comment]
https://github.com/gajus/create-index/issues/26
