### ISSUE TITLE
[bug] can't read file or folder with "-"?

### ISSUE THREAD

**Issue by kud** [gajus/create-index#57]
Hello,

I wanted to create an index of some files or folders with "-" and I saw that an empty index with just the banner was created.

So I tried to rename my folders or files and now it works.

![image](https://user-images.githubusercontent.com/655838/81457869-2c268580-9198-11ea-9edd-14e775a3aaa4.png)

As you can see, only the one without "-" worked.

**Comment by kud** [comment]
Oh okay, in fact you don't read the export but the name of the file, like I've got:

```
const getLangFromPathname = (pathname) => pathname.split("/")[1]

export default getLangFromPathname
```

I tought it was easy to get `getLangFromPathname` here where the file is named `get-lang-from-pathname.js`.

But as I think you read the name of the file, which is perfectly fine but a conversion from `kebab-case` to `lowerCamelCase` should be the trick.

**Comment by gajus** [comment]
No plan to support kebab-case. See previous discussions.

**Comment by kud** [comment]
Do you mind if I do a PR about this? or should I fork your project?

**Comment by gajus** [comment]
There were several PRs for this already. I think there are a few forks for this too.

**Comment by kud** [comment]
Yes, just saw "create-index-plus". Thank you for your time!
