### ISSUE TITLE
Make target file extension configurable

### ISSUE THREAD

**Issue by gausie** [gajus/create-index#6]
I use `.jsx` in my project (for ReactJS) so this currently will not work on my components folder.

I could submit a pull request but wondered if you want to support user-configured extensions.

**Comment by gajus** [comment]
By the looks of it, this change would affect only a few lines of code:

```js
./src/utilities/readDirectory.js:36:        return !_.includes(files, fileName + '.js');
./src/utilities/readDirectory.js:67:        if (!isDirectory && !_.endsWith(fileName, '.js')) {
```

As long as this feature is implemented sticking to principles of functional programming (without use or global state variables and tested), I don't have any objections against a PR.

**Comment by gausie** [comment]
I figured I would just replace with `fileName.matches(/\.jsx?$/)`

**Comment by gajus** [comment]
No, that could have unwanted side-effects.

Someone could have `Foo.js` as entry file and `Foo.jsx` to contain a template. Not saying it is a good thing to do, but I have seen worse and it is fairly likely scenario.

**Comment by Someguy123** [comment]
What's the status of this? @gajus ?

Would be great to just do `--filetype=jsx`, or if it would just natively do JSX by default.

**Comment by gajus** [comment]
> What's the status of this? @gajus ?

Not a priority for me. Will happily accept a PR.

**Comment by jogelin** [comment]
It is also useful for typescript but it doesn't generate index.TS...

**Comment by gajus** [comment]
> It is also useful for typescript but it doesn't generate index.TS...

Would accept a PR.

**Comment by FDiskas** [comment]
already implemented
