### ISSUE TITLE
Dashes in filename

### ISSUE THREAD

**Issue by willcode4food** [gajus/create-index#8]
I seem to be having an issue with dashes in filenames.  The index file gets created, but is empty.

thanks

**Comment by gajus** [comment]
Dash cannot be part of a valid export name.

**Comment by willcode4food** [comment]
Thanks for the quick response.  Is this by design or a limitation of the methods to parse filenames?

**Comment by gajus** [comment]
As far as I know, there is no spec/ proposal that would allow to export a name consisting a dash, e.g.

```js
export 'foo-bar' from './foo-bar';
```

is not a valid JavaScript code.

If I am wrong and it is valid JavaScript code, then it is a trivial fix.

Regardless, looking at http://babeljs.io/repl/#?evaluate=true&presets=es2015%2Creact%2Cstage-0&experimental=true&loose=false&spec=false&code=export%20'foo-bar'%20from%20'.%2Ffoo-bar'%3B, it does not look like above is valid syntax.

**Comment by willcode4food** [comment]
I understand.  I am trying to do something more like this

`export 'foobar' from './foo-bar'`

**Comment by gajus** [comment]
`create-index` does not perform any sort of name normalisation.

**Comment by willcode4food** [comment]
Understood.  thanks for the info.  I'll move in another direction

**Comment by gajus** [comment]
I strongly encourage to have 1=1 to relation between import files and variables representing the asset.

**Comment by willcode4food** [comment]
Agreed this is ideal. When working on someone else's code, I'm trying to be as unintrusive as possible.  This discussion makes me realize, perhaps renaming files might be something I need to discuss with the repo owner.

thanks

**Comment by jakesyl** [comment]
I've gone ahead and forked it here: https://github.com/jakesyl/create-index-normalized to camelCase names with a - for anyone interested. @gajus would be cool to have a camelcase option
